development:
  adapter: postgresql
  encoding: unicode
  database: hello_development
  pool: 5
  host: localhost
  username: newton
  password: 12345

test:
  adapter: postgresql
  encoding: unicode
  database: hello_test
  pool: 5
  username: newton
  password: 12345

# staging:
#   url: <%= ENV['DATABASE_URL'] %>

# production:
#   url: <%= ENV['DATABASE_URL'] %>